"""add_targeting_rules_versions_audit

Revision ID: 5fa0f9148cb7
Revises: 40d0db0320fc
Create Date: 2026-06-23 00:11:03.701344
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5fa0f9148cb7"
down_revision = '40d0db0320fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###