"""add_targeting_rules_versions_audit

Revision ID: d791af82e2ab
Revises: 5fa0f9148cb7
Create Date: 2026-06-23 00:17:03.662318
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d791af82e2ab"
down_revision = '5fa0f9148cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'targeting_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flag_id', sa.Integer(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('serve_value', sa.Boolean(), nullable=False),
        sa.Column('conditions', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'feature_flag_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flag_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('state_snapshot', sa.JSON(), nullable=False),
        sa.Column('changed_by', sa.String(length=100), nullable=False),
        sa.Column('change_reason', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flag_key', sa.String(length=64), nullable=False),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('changed_by_username', sa.String(length=100), nullable=False),
        sa.Column('details', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_flag_key'), 'audit_logs', ['flag_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_flag_key'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('feature_flag_versions')
    op.drop_table('targeting_rules')
    # ### end Alembic commands ###